version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s | %(name)s | %(levelname)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: app-log.log

root:
  level: INFO
  handlers: [console, file]